"""empty message

Revision ID: 66414ebbf71a
Revises: 
Create Date: 2026-03-07 17:50:30.303722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66414ebbf71a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index('idx_post_path', ['com_postid', 'path'], unique=False, mysql_length={'path': 255})

    with op.batch_alter_table('salesrep', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lga', ['sr_lgaid'], ['lga_id'])
        batch_op.create_foreign_key(None, 'state', ['sr_stateid'], ['state_id'])

    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spadmin_password_changed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_column('spadmin_password_changed_at')

    with op.batch_alter_table('salesrep', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('idx_post_path', mysql_length={'path': 255})

    # ### end Alembic commands ###
