"""empty message

Revision ID: df6a49e5334b
Revises: 66414ebbf71a
Create Date: 2026-03-08 14:57:20.788245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6a49e5334b'
down_revision = '66414ebbf71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_attempt_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_locked_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_attempt_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_locked_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('designer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_attempt_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_locked_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('salesrep', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lga', ['sr_lgaid'], ['lga_id'])
        batch_op.create_foreign_key(None, 'state', ['sr_stateid'], ['state_id'])

    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_attempt_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_column('reset_locked_until')
        batch_op.drop_column('reset_attempt_time')
        batch_op.drop_column('reset_attempts')

    with op.batch_alter_table('salesrep', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('designer', schema=None) as batch_op:
        batch_op.drop_column('reset_locked_until')
        batch_op.drop_column('reset_attempt_time')
        batch_op.drop_column('reset_attempts')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('reset_locked_until')
        batch_op.drop_column('reset_attempt_time')
        batch_op.drop_column('reset_attempts')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('reset_locked_until')
        batch_op.drop_column('reset_attempt_time')
        batch_op.drop_column('reset_attempts')

    # ### end Alembic commands ###
